# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberinfosanlamdatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAMILY_NO', models.CharField(blank=True, max_length=255)),
                ('MEMBER_NO', models.CharField(blank=True, max_length=255)),
                ('FIRST_NAME', models.CharField(blank=True, max_length=255)),
                ('SURNAME', models.CharField(blank=True, max_length=255)),
                ('OTHER_NAMES', models.CharField(blank=True, max_length=255)),
                ('DOB', models.CharField(blank=True, max_length=255)),
                ('USER_ID', models.CharField(blank=True, max_length=255)),
                ('CANCELLED', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
