# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-06 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20180306_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_info',
            name='cancelled',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='date_entered',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='family_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='first_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='gender',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='member_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='other_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='passport_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='surname',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='user_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
