# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-06 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20180306_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_info',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
