# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-06 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20180306_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_info',
            name='date_entered',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='dob',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
