# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 15:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (9 - 15 digits).', regex='^[0-9][a-z][A-Z]{9,15}$')], verbose_name='phone number'),
        ),
    ]
