# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180305_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_patient',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the website.'),
        ),
    ]
