# Generated by Django 3.0.1 on 2020-08-07 10:59
from django.db import migrations
from django.contrib.auth.models import Permission


def forwards_func(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    group,created = Group.objects.get_or_create(name='Superadmin')
    if created:
        permissions = Permission.objects.filter(name='create_deactivate_user')
        for p in permissions:
            group.permissions.add(p)
        group.save()

    # Create the groups you need here...


def reverse_func(apps, schema_editor):
    # will be run if migrations are reversed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_emaillog'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
