# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='examination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='his_presenting_illness',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='plan_of_managemnt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='prescription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='query_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='radiology_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='triage_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
