# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patientvisit_attending_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiologylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=255)),
                ('modality', models.CharField(blank=True, max_length=255)),
                ('tests', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
