# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_radiologylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
