# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20180327_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
