<<<<<<< HEAD
# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20180327_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='diag_search',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20180327_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='diag_search',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
>>>>>>> 037b6d71d45035c58b96fc5d43770f0b5c23cb0f
