# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='age',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='name',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='County',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='insurancecompanies',
            name='Name',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='medication',
            name='age',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicationhistory',
            name='Disease',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alcohol_frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alocohol_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caffein_daily_amt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cigar_per_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='exercise_freq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='have_will',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='if_chew_tobacco',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='if_drink_alcohol',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='if_drug_used',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='if_exercise',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='if_lost_interest',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='if_quit_before',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='if_smoker',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='if_special_diet',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='if_use_caffein',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_sadder',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='living_children',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, default='Single', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='no_of_yr_smoking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='spouse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tobacco_quit_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='when_drug_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='yrs_chewing_tobacco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
