# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180302_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pri_ins_sub',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sec_ins_sub',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
