# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180302_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sub_id_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
