# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180304_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='physical_address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
