# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_patient_physical_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('child_name', models.CharField(blank=True, default='NO', max_length=255, null=True)),
                ('child_age', models.CharField(blank=True, default='NO', max_length=255, null=True)),
                ('patient_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='registration.Patient', verbose_name='patient_no')),
            ],
            options={
                'verbose_name': 'child',
                'verbose_name_plural': 'children',
                'ordering': ('last_updated',),
            },
        ),
        migrations.RemoveField(
            model_name='children',
            name='patient_no',
        ),
        migrations.DeleteModel(
            name='Children',
        ),
    ]
