# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180312_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='patient_no',
        ),
        migrations.RemoveField(
            model_name='child',
            name='child_age',
        ),
        migrations.AddField(
            model_name='child',
            name='child_dob',
            field=models.CharField(blank=True, default=datetime.datetime(2018, 3, 16, 13, 9, 39, 580031), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='child_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
