# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20180316_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
