# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='unique1@redpulse.co.ke', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
