# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20180322_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
