# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_patient_terminations'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
