# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_patient_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
