# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_auto_20180301_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='models',
            new_name='Nurse',
        ),
    ]
