# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_patient_county'),
        ('nurse', '0003_auto_20180319_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='nurse',
            name='patient_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to='registration.Patient', verbose_name='patient_no'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='patient_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='patient_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
